global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'rabbitmq_consumer'
    static_configs:
      - targets: ['host.docker.internal:2112']  # Для Windows используйте host.docker.internal вместо localhost